// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxDmVKoVzuBOlziZcINo8TZNZp-LJZy7I',
    appId: '1:380186307137:android:ef2e83a493797ed00bb4c0',
    messagingSenderId: '380186307137',
    projectId: 'beatrush-d7050',
    databaseURL: 'https://beatrush-d7050-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'beatrush-d7050.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOcxaTxEfERoE7qyvDdCxSREIuMFbmMOo',
    appId: '1:380186307137:ios:564e6f89e36058000bb4c0',
    messagingSenderId: '380186307137',
    projectId: 'beatrush-d7050',
    databaseURL: 'https://beatrush-d7050-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'beatrush-d7050.firebasestorage.app',
    iosBundleId: 'com.example.beatRush',
  );
}
